services:
  - type: web
    name: samadhan-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: WATSONX_API_KEY
        sync: false
      - key: WATSONX_DEPLOYMENT_ID
        sync: false
      - key: WATSONX_URL
        sync: false
      - key: WATSONX_VERSION
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
